### ISSUE TITLE
Please delete tag: refs/heads/master

### ISSUE THREAD

**Issue by cognifloyd** [ansible-collections/community.mongodb#163]
##### SUMMARY
There is a bogus git tag that makes pushing to a fork difficult. I was trying to bring my fork's master up-to-date. When I push, I get:

```
error: dst refspec refs/heads/master matches more than one
error: failed to push some refs to 'git@github.com:cognifloyd/community.mongodb.git'
```

I've deleted the `refs/heads/master` tag (yes, tag, not a branch) from my fork, but every time I `git fetch --all` from my upstream remote (this repo) to get any new release tags, it also re-adds the bad tag.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
git

##### HOW TO FIX
Someone with commit access to this repo, please (1) delete the tag locally, and then (2) delete the tag on github.

```
git tag -d refs/heads/master
git push origin :refs/tags/refs/heads/master
```

Tested with my fork.

**Comment by cognifloyd** [comment]
Looks like the `refs/pull/62/merge` tag was also a mistake. The same process will work to delete that tag as well.
```
git tag -d refs/pull/62/merge
git push origin :refs/tags/refs/pull/62/merge
```

**Comment by rhysmeister** [comment]
Done.

**Comment by rhysmeister** [comment]
The tag "refs/heads/master -> refs/heads/master" gets readded in the automation that builds the collection archive for other CI jobs...

https://github.com/ansible-collections/community.mongodb/blob/master/.github/workflows/publish_collection.yml

I'm guessing the svenstaro/upload-release-action@v1-release action does this.

**Comment by rhysmeister** [comment]
It should work if I add a specific tag "latest" and update the CI to use that. Might take a day or two to get around to it.

**Comment by cognifloyd** [comment]
Yeah this is where it's selecting master.
https://github.com/ansible-collections/community.mongodb/blob/3de09fed1c4e4fdb1a444f72479fe94e751c4f00/.github/workflows/publish_collection.yml#L4-L5

Also, if we switch to a svenstaro/upload-release-action@master instead of svenstaro/upload-release-action@v1-release, that strips the refs/heads/ from tag names. That might be another part of it.

**Comment by rhysmeister** [comment]
OK. Task now uses the tag "latest". I'll leave this open until the CI runs through again to confirm all is ok. Cheers, R

**Comment by rhysmeister** [comment]
All looks good.
