### ISSUE TITLE
Set no_log for update_password in mongodb_user module

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#187]
##### SUMMARY
Ansible spits out the following warning when we use the mongodb_user module...

[WARNING]: Module did not set no_log for update_password

Let's add no_log to this parameter. Not super important but prevents the unneeded nag.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_user

**Comment by cognifloyd** [comment]
Fixed in #192
