### ISSUE TITLE
mongodb_info tests

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#20]
##### SUMMARY

These tests should probably use the standard setup_mongodb process like the others.

##### ISSUE TYPE
- Feature Idea

**Comment by rhysmeister** [comment]
Tests are CentOS only and are skipped with the new ansible-test process which is Ubuntu only.

**Comment by gundalow** [comment]
You can change 
https://github.com/ansible-collections/mongodb/blob/7efa18fe9bf160e48c8c8e4b62d92f62473544ed/.github/workflows/ansible-test.yml#L49

to be `--docker OS` using any of the operating systems listed here https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/completion/docker.txt

**Comment by rhysmeister** [comment]
Implemented in https://github.com/ansible-collections/mongodb/pull/51
