### ISSUE TITLE
Playbooks question

### ISSUE THREAD

**Issue by gwbischof** [ansible-collections/community.mongodb#204]
I am about to write a playbook to install the ssl sharded cluster on vagrant vms.

Is this file a good starting point to run all of the modules to setup the cluster?
https://github.com/ansible-collections/community.mongodb/blob/master/tests/integration/targets/mongodb_shard/tasks/ssl_sharded_cluster.yml

Does anyone have a example playbook/inventory file to do the full install?

Would the vagrantfile be useful to anyone?

Thanks!

**Comment by rhysmeister** [comment]
Hello,

Not sure about that Playbook. That was contributed by a user for testing a specific type of authentication. I have a separate project here for MongoDB Deployments...

https://github.com/rhysmeister/AutomatingMongoDBWithAnsible/tree/master/playbooks/sharded_cluster

Rhys

**Comment by gwbischof** [comment]
Thanks! This is really helpful! I'll try to contribute if I come up with anything useful
