### ISSUE TITLE
Drop testing with py2.7 in Travis

### ISSUE THREAD

**Issue by cognifloyd** [ansible-collections/community.mongodb#228]
##### SUMMARY
Python 2.7 is EOL.
Python2.7 is a blocker for upgrading molecule.

I think there are two things, the module tests in the CI workflow (github actions), and the molecule role tests (Travis CI).
What do you think of removing 2.7 from Travis so that we can upgrade molecule?
Essentially, that would mean deprecating support for 2.7 on controller-side, but not host-side. For our roles, I don't think that would be a problem.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
python2.7 deprecation

**Comment by cognifloyd** [comment]
Thinking about this a bit more, I don't have a problem keeping py2.7 support for any of the plugins: lookups, cache on controller-side, and modules on host-side.
But I don't think there's any value in testing the roles on python2.7 - there is nothing in the roles that would differ between python2.7 and python3.

**Comment by cognifloyd** [comment]
I suppose the only place it would matter would be for people running molecule tests locally. But using legacy python in that case is still not a good idea because python 2.7 is EOL and the latest molecule doesn't support it.

The latest molecule doesn't support python 3.5 either. Can we switch travis to test with python3.6+ only?

**Comment by rhysmeister** [comment]
This has crossed my mind once or twice. CentOS 7 uses py2.7 and was released in 2014-07-07 and updates stopped on 2020-08-06. I think we can keep testing on py2.7 for modules and other plugins but let's go ahead and go with your suggestion for 3.6+ only for Travis roles. I think we should probably do a Galaxy release first though.

**Comment by rhysmeister** [comment]
Done in https://github.com/ansible-collections/community.mongodb/pull/232
