### ISSUE TITLE
"no such command: 'force' in module mongodb_stepdown

### ISSUE THREAD

**Issue by julienpaulino** [ansible-collections/community.mongodb#263]
##### SUMMARY
mongodb_stepdown failled in error on primary node
fatal: [10.100.199.201]: FAILED! => {"changed": false, "iterations": 1, "msg": "no such command: 'force', full error: {u'code': 59, u'ok': 0.0, u'lastCommittedOpTime': Timestamp(1608799790, 1), u'$clusterTime': {u'clusterTime': Timestamp(1608799790, 1), u'signature': {u'keyId': 6909391941515870239L, u'hash': Binary('\\x99o$\\rB@\\xe9\\x06\\xc0\\x04\\xe1l\\xfeOW)\\x01P\\xf5Z', 0)}}, u'codeName': u'CommandNotFound', u'operationTime': Timestamp(1608799790, 1), u'errmsg': u\"no such command: 'force'\"}"} 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_stepdown

##### ANSIBLE VERSION
```
[vagrant@salt-master ansible]$ ansible --version
ansible 2.10.4
  config file = /srv/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### CONFIGURATION
```
[vagrant@salt-master ansible]$ ansible-config dump --only-changed
HOST_KEY_CHECKING(/srv/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS 7.7

##### STEPS TO REPRODUCE
Execute the following playbook on a primary node

```
- hosts: mongo-config
  serial: 1
  tasks:
    - name: Start the secondary config servers
      service:
        name: mongo-config
        state: started
      become: true
    - name: Step Down if primary config servers
      community.mongodb.mongodb_stepdown:
        login_user: root
        login_password: root
        login_port: 27019
        stepdown_seconds: 30
        secondary_catch_up: 10
```

##### EXPECTED RESULTS
The primary node should step down and become secondary

##### ACTUAL RESULTS
Failled in error
```
<10.100.199.201> SSH: EXEC sshpass -d9 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="vagrant"' -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/d4cee2cb2e 10.100.199.201 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1608800463.1506777-8610-17199575178883/ > /dev/null 2>&1 && sleep 0'"'"''
<10.100.199.201> (0, b'', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 8233\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_community.mongodb.mongodb_stepdown_payload_gd132Z/ansible_community.mongodb.mongodb_stepdown_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_stepdown.py", line 280, in main
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 740, in command
    codec_options, session=session, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 637, in _command
    client=self.__client)
  File "/usr/lib64/python2.7/site-packages/pymongo/pool.py", line 694, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/lib64/python2.7/site-packages/pymongo/network.py", line 161, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/lib64/python2.7/site-packages/pymongo/helpers.py", line 160, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
fatal: [10.100.199.201]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_mechanism": null,
            "connection_options": null,
            "force": false,
            "interval": 30,
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": 27019,
            "login_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "poll": 1,
            "secondary_catch_up": 10,
            "ssl": false,
            "ssl_ca_certs": null,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "ssl_certfile": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_pem_passphrase": null,
            "stepdown_seconds": 30
        }
    },
    "iterations": 1,
    "msg": "no such command: 'force', full error: {u'code': 59, u'ok': 0.0, u'lastCommittedOpTime': Timestamp(1608800461, 1), u'$clusterTime': {u'clusterTime': Timestamp(1608800461, 1), u'signature': {u'keyId': 6909391941515870239L, u'hash': Binary('\\xe9e\\xe3\\xb2\\xf9\\x1aU\\xda,\\x1e\\xcf\\xe8 \\xdevU\\xcb\\xad>\\x86', 0)}}, u'codeName': u'CommandNotFound', u'operationTime': Timestamp(1608800461, 1), u'errmsg': u\"no such command: 'force'\"}"
```

**Comment by rhysmeister** [comment]
Hello @julienpaulino what version of mongod are you using?

**Comment by julienpaulino** [comment]
Hello @rhysmeister 
It's a 4.0.21

**Comment by rhysmeister** [comment]
I can't seem to replicate this on 4.0.22 (just happened to have a cluster with this version available). I can't see anything in the release notes that would indicate a behaviour change in the replSetStepDown command this module uses.

Possible fix in https://github.com/ansible-collections/community.mongodb/pull/264

Previously I always added the force field to the command doc. Now I only add it when it's set to true. Can you try executing the following on a 4.0.21 instance...

`db.adminCommand({ 'replSetStepDown': 30,  'secondaryCatchUpPeriodSecs': 10, 'force': false})`

**Comment by julienpaulino** [comment]
Executing the command directly in the mongo shell works correctly:

configReplSet01:PRIMARY> db.adminCommand({ 'replSetStepDown': 30, 'secondaryCatchUpPeriodSecs': 10, 'force': false})
2020-12-24T11:44:26.665+0000 I NETWORK  [js] DBClientConnection failed to receive message from 127.0.0.1:27019 - HostUnreachable: Connection closed by peer
2020-12-24T11:44:26.674+0000 E QUERY    [js] Error: error doing query: failed: network error while attempting to run command 'replSetStepDown' on host '127.0.0.1:27019'  :
DB.prototype.runCommand@src/mongo/shell/db.js:168:1
DB.prototype.adminCommand@src/mongo/shell/db.js:185:1
@(shell):1:1
2020-12-24T11:44:26.677+0000 I NETWORK  [js] trying reconnect to 127.0.0.1:27019 failed
2020-12-24T11:44:26.678+0000 I NETWORK  [js] reconnect 127.0.0.1:27019 ok

**Comment by julienpaulino** [comment]
Calling rs.stepDown() with mongodb_shell works also:

```
- name: Step Down if primary config servers
  community.mongodb.mongodb_shell:
    login_user: root
    login_password: root
    login_port: 27019
    eval: "rs.stepDown()"
  ignore_errors: true
  register: step
  when: inventory_hostname == primary
```

**Comment by rhysmeister** [comment]
Hi @julienpaulino,

I'm unable to replicate this on a cluster I downgraded to 4.0.21. Could you paste the output from the following command...

`ansible-galaxy collection list`

**Comment by julienpaulino** [comment]
[vagrant@salt-master ansible]$ ansible-galaxy collection list

# /home/vagrant/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
ansible.netcommon    1.4.1  
community.docker     1.0.1  
community.general    1.3.1  
community.kubernetes 1.1.1  
community.mongodb    1.1.1  
google.cloud         1.0.1

**Comment by rhysmeister** [comment]
Mmmmm, same version I'm using. Can I have the following file?

/home/vagrant/.ansible/collections/ansible_collections/community/mongodb/plugins/modules/mongodb_stepdown.py

I assume you're installing straight from ansible-galaxy?

**Comment by julienpaulino** [comment]
Yes using that command: ansible-galaxy collection install community.mongodb

[mongodb_stepdown.zip](https://github.com/ansible-collections/community.mongodb/files/5739675/mongodb_stepdown.zip)

**Comment by rhysmeister** [comment]
OK. As expected that's the same version of the file I'm testing against. It's a fairly simple module and there's not been much in the way of changes since I created it. Is this repeatable? Are there any differences on your side that might be relevant?

The latest version contains a small code change that you could try...

`
wget https://github.com/ansible-collections/community.mongodb/releases/download/latest/community-mongodb-latest.tar.gz;
ansible-galaxy collection install community-mongodb-latest.tar.gz --force;
`

**Comment by julienpaulino** [comment]
Same error with the latest version too...
I don't see any differences, only that I'm running it in a vagrant box.

**Comment by rhysmeister** [comment]
Mmmm, I've just had a thought. Perhaps the dict I build is being reordered. I've had this problem before. Python dicts do not always preserve the order of keys. I should be using the OrderedDict class here. You're probably using a version of Python that, for some reason, changes the order of the keys and thus 'force' is first.

**Comment by rhysmeister** [comment]
@julienpaulino I've merged a fix that should resolve the issue.

**Comment by julienpaulino** [comment]
@rhysmeister Thanks for the quick fix it's working now!!
