### ISSUE TITLE
mongodb_info produces incorrect output when user/role names exist in multiple database

### ISSUE THREAD

**Issue by juusom** [ansible-collections/community.mongodb#283]
##### SUMMARY

MongoDB users are [specific to databases](https://docs.mongodb.com/manual/core/security-users/#user-authentication-database), and therefore a user by the same name can exist in multiple databases. Currently, the mongodb_info role builds a dictionary keyed by username, so when the same username exists in multiple DBs, whichever DB happens to be iterated last will end up in the result.

Here's where it happens:
https://github.com/ansible-collections/community.mongodb/blob/f9e4bb4b556663dbfbe730537e3f2d765900f6f3/plugins/modules/mongodb_info.py#L193-L195

The same applies to roles.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_info

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Create a user by the same name in multiple databases in the same mongo instance/replica set/cluster and run mongodb_info.

##### EXPECTED RESULTS
All users should be returned. I can think of a number of ways to do it, but they're all more or less breaking changes - for example returning just a list, or adding a further nesting layer keyed by database name, or changing the key from `user` to `db.user`.

##### ACTUAL RESULTS
Each username will appear in the output only once, even if defined separately in multiple databases.

**Comment by rhysmeister** [comment]
Possible fix in https://github.com/ansible-collections/community.mongodb/pull/285

**Comment by juusom** [comment]
That was quick!
