### ISSUE TITLE
gh-pages (docs) vs https://docs.ansible.com/ansible/latest/collections/community/mongodb/

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.mongodb#317]
Hi @rhysmeister 
I notice you have a `gh-pages` branch and a cool GH action to build the module docs

Did you know that as `community.mongodb` is included in the `ansible` package we automatically build docs here https://docs.ansible.com/ansible/latest/collections/community/mongodb/

This appears to contain the same as https://ansible-collections.github.io/community.mongodb/

**Comment by rhysmeister** [comment]
Hello John,

Yes I know this. The GHA is just there to provide the "bleeding edge" docs that I can look at before an official release.

Cheers,

Rhys

**Comment by rhysmeister** [comment]
Closing. Reopen if there's anything further,
