### ISSUE TITLE
Localhost exception not working

### ISSUE THREAD

**Issue by coyotte508** [ansible-collections/community.mongodb#333]
##### SUMMARY

`mongodb_auth` does not succed in creating the first user. The error is as below:

```
TASK [community.mongodb.mongodb_auth : Add mongo admin user with localhost exception] ************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotMasterError: not master, full error: {u'topologyVersion': {u'processId': ObjectId('60a57d4af5b2571aaaa80155'), u'counter': 0L}, u'code': 10107, u'ok': 0.0, u'codeName': u'NotWritablePrimary', u'errmsg': u'not master'}
fatal: [54.36.115.118]: FAILED! => {"changed": false, "msg": "Unable to add or update user: not master, full error: {u'topologyVersion': {u'processId': ObjectId('60a57d4af5b2571aaaa80155'), u'counter': 0L}, u'code': 10107, u'ok': 0.0, u'codeName': u'NotWritablePrimary', u'errmsg': u'not master'}"}
```

The error disappears if `replicaset: false` is set during the `mongodb_mongod` stage.

The localhost exception does not seem to work if `mongod` is launched with a replicaset config but the replicaset has not been initiated with `rs.initiate()`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mongodb_auth

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = None
  configured module search path = ['/home/ecoyac/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
<empty>
```

##### OS / ENVIRONMENT

WSL2

##### STEPS TO REPRODUCE

This is the playbook run on a fresh debian 10 install

```yaml
---
- name: "Install pymongo"
  hosts: databases
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Install or update pip
      apt:
        pkg: python-pip
        state: present
    - pip:
        name: pymongo

- hosts: databases
  collections:
    - community.mongodb
  roles:
    - { role: mongodb_repository }
    - { role: mongodb_mongod }
    - { role: mongodb_auth, mongodb_admin_pwd: f00b@r, mongod_host: 127.0.0.1 }
  become: true
  become_user: root
  become_method: sudo
```

##### EXPECTED RESULTS

The admin user is created

##### ACTUAL RESULTS

The admin user is not created

```paste below
TASK [community.mongodb.mongodb_auth : Add mongo admin user with localhost exception] ************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotMasterError: not master, full error: {u'topologyVersion': {u'processId': ObjectId('60a57d4af5b2571aaaa80155'), u'counter': 0L}, u'code': 10107, u'ok': 0.0, u'codeName': u'NotWritablePrimary', u'errmsg': u'not master'}
fatal: [54.36.115.118]: FAILED! => {"changed": false, "msg": "Unable to add or update user: not master, full error: {u'topologyVersion': {u'processId': ObjectId('60a57d4af5b2571aaaa80155'), u'counter': 0L}, u'code': 10107, u'ok': 0.0, u'codeName': u'NotWritablePrimary', u'errmsg': u'not master'}"}
```

##### SOLUTIONS

Document the need to instantiate the replicaset first, or disable it. As it is, the given sample playbook given in https://github.com/ansible-collections/community.mongodb/tree/master/roles/mongodb_auth does not work

**Comment by coyotte508** [comment]
Currently this is the best way I found to create a replicaset and an admin user:

- mongodb_mongod
- mongodb_replicaset to initiate the replica_set (try first with no login, try again with login)
- delay a few seconds if previous task "changed"
- mongodb_auth on the replicaset to add the admin user / other users

**Comment by rhysmeister** [comment]
Hi @coyotte508,

The behaviour you see if consistent with how the localhost exception works...

https://docs.mongodb.com/manual/core/security-users/#localhost-exception

But you are right that the documentation is incorrect. I will get this fixed.

Thanks,

Rhys

**Comment by rhysmeister** [comment]
Updated documentation in https://github.com/ansible-collections/community.mongodb/pull/334
