### ISSUE TITLE
TODO: Remove unused imports from modules

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#340]
##### SUMMARY

Remove unused imports from modules.

```
rhyss-mbp:mongodb rhyscampbell$ importchecker plugins/modules/mongodb_monitoring.py
plugins/modules/mongodb_monitoring.py:75: binary_type, text_type
plugins/modules/mongodb_monitoring.py:76: configparser
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
All modules.

**Comment by 116davinder** [comment]
@rhysmeister, I have created a PR for it.
when you have time, you can review it

**Comment by rhysmeister** [comment]
Hello @116davinder,

A few problems...

https://github.com/ansible-collections/community.mongodb/pull/399/checks?check_run_id=3800122536

There's probably an import or two that needs to return. The tool probably doesn't consider dependancies between files.

Rhys

**Comment by rhysmeister** [comment]
Merged
