### ISSUE TITLE
mongodb_linux role depends on the ansible.posix collection

### ISSUE THREAD

**Issue by cognifloyd** [ansible-collections/community.mongodb#351]
##### SUMMARY
The `mongodb_linux` role depends on the `ansible.posix` collection, but that is not documented or listed in dependencies.

`ansible.posix` provides the `sysctl` module. I installed ansible with `ansible-core` instead of `ansible` to avoid getting all the bundled collections. I got an error with the `mongodb_linux` role:
```
ERROR~ couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.
```

Installing the `ansible.posix` collection resolves the issue.

Do we need to add this anywhere other than `galaxy.yml`?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_linux role

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.2]
  config file = /[snip]/ansible/ansible.cfg
  ...
  python version = 3.6.8 ...
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection               Version
------------------------ -------
ansible.posix            1.2.0
cognifloyd.st2_installer 0.1.0
community.general        3.3.2
community.mongodb        1.2.1 (latest from 2021-07-12)  
community.rabbitmq       1.0.3
```

##### OS / ENVIRONMENT
CentOS 7

**Comment by cognifloyd** [comment]
btw: This is not visible in our role tests because all the role tests still use ansible 2.9 which still has `sysctl` bundled. Only newer versions of `ansible-core` (which used to be called `ansible-base`) have moved it into the `ansible.posix` collection.

**Comment by rhysmeister** [comment]
Yes, this makes sense. There were actually a bunch of dependancies due to a few includes. I think community.general depended on a single function on either google.cloud or the community.kubernetes collections, which in turn pulled down a bunch of other collections. There might be another surprise or two related to this.
