### ISSUE TITLE
mongo shell eval ignores ":"

### ISSUE THREAD

**Issue by denzhel** [ansible-collections/community.mongodb#365]
I have this test playbook:
```
- name: "mongo test"
  hosts: localhost
  tasks:
    - name: "Run the listDatabases command"
      community.mongodb.mongodb_shell:
        debug: yes
        quiet: no
        db: "test"
        eval: 'db.organizations.update({"name": "test"},{"$set" : {"feature_toggles.test": false}})'
        transform: json
```
When I run it I get this error:
```
msg": "uncaught exception: SyntaxError: missing : after property id :\n@(shell eval):1:69\nexiting with code -4"
```

I tried running the eval command manually in various ways and it worked:
* mongo shell 3.2.22 / mongo shell 5.0
* Robo3T

Please help.

**Comment by rhysmeister** [comment]
Hello @denzhel,

Can you try escaping the $ in your eval? i.e.

```
db.organizations.update({"name": "test"},{"\$set" : {"feature_toggles.test": false}})
```

Rhys

**Comment by denzhel** [comment]
@rhysmeister Thank you for responding ! 

I get the same error :(

**Comment by denzhel** [comment]
@rhysmeister Wow .. thanks !!! The fastest issue fixer award definitely goes to you ! :)

**Comment by rhysmeister** [comment]
No problem. It should be possible to make the current version work given the correct escaping. But that can get a bit ugly/complicated. This is better.

**Comment by rhysmeister** [comment]
FIx merged. Can be installed via https://github.com/ansible-collections/community.mongodb/releases/tag/latest
