### ISSUE TITLE
Module refactoring - mongo_auth

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#377]
##### SUMMARY
In this pull for mongodb_replicaset https://github.com/ansible-collections/community.mongodb/pull/376 I have refactored the auth stuff into mongodb_common.py. If this works out this should be implemented in all relevant modules.

This would involve...

- Removing all auth code.
- Removing some login_XXXXXX variables from the main module section.
- Adding mongo_auth to mongodb_common imports.
- Adding the function call at the correct place.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
All modules

**Comment by rhysmeister** [comment]
1. Remove block of code starting with

`if login_user is None and login_password is None:`

And ending with

`module.fail_json(msg='Unable to authenticate with MongoDB: %s' % to_native(excep))`

2. Remove 

```
    login_user = module.params['login_user']
    login_password = module.params['login_password']
    login_database = module.params['login_database']
```

3. Add  mongo_auth function to imports

4. Add call to function where appropriate

`mongo_auth(module, client)`

Probably where you removed the code in #1

**Comment by cognifloyd** [comment]
Nice! Cleaning up the repeated blocks sounds fabulous.

**Comment by rhysmeister** [comment]
Yes, it's about time I did it. Sadly there's a few differences in the workflow esp replicaset and user modules. Hopefully this can all be generalised.

**Comment by rhysmeister** [comment]
Merged: https://github.com/ansible-collections/community.mongodb/pull/378
