### ISSUE TITLE
Plugin doc is broken on the docsite

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.mongodb#386]
##### SUMMARY
If we click the plugins on https://docs.ansible.com/ansible/devel/collections/community/mongodb/, it will return errors.

To fix the issue these two lines have to go: https://github.com/ansible-collections/community.mongodb/blob/master/plugins/lookup/mongodb.py#L25 https://github.com/ansible-collections/community.mongodb/blob/master/plugins/cache/mongodb.py#L11

Thanks @felixfontein

**Comment by rhysmeister** [comment]
Done: https://github.com/ansible-collections/community.mongodb/pull/387

Thanks for the heads up.

**Comment by rhysmeister** [comment]
Merged.
