### ISSUE TITLE
Unable to initialize replicaset: requires authentication (MongoDB with authentication enabled but no SSL)

### ISSUE THREAD

**Issue by qaoru** [ansible-collections/community.mongodb#422]
##### SUMMARY

I am unable to initialize a replicaset using `mongodb_replicaset` (authentication error).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`mongodb_replicaset`

##### ANSIBLE VERSION

```
ansible [core 2.11.4] 
  config file = /home/pheng/.ansible.cfg
  configured module search path = ['/home/pheng/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pheng/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/pheng/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/pheng/.local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/pheng/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.3.2  

# /home/pheng/.local/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.3.1 
```

##### CONFIGURATION

```
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/pheng/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/pheng/.ansible.cfg) = yaml
```

##### OS / ENVIRONMENT

Ubuntu 20.04
MongoDB 4.0.23 on remote servers

##### STEPS TO REPRODUCE

Try the `mongodb_replicaset` module on an existing database with authentication enabled.

```yaml
- name: configure replicaset
  community.mongodb.mongodb_replicaset:
    login_host: '127.0.0.1'
    login_user: root
    login_password: ****
    login_database: admin
    replica_set: "{{ rs_name }}"
    members: "{{ groups[rs_name] | zip_longest([], fillvalue=':27017') | map('join') | list}}"
  when: "'primary' in group_names"
```

##### EXPECTED RESULTS

ReplicaSet is initialized correctly.

##### ACTUAL RESULTS

Command failed due to authentication issues.
See below :

```
The full traceback is:
  File "/tmp/ansible_community.mongodb.mongodb_replicaset_payload_z89e7xq0/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py", line 602, in main
  File "/tmp/ansible_community.mongodb.mongodb_replicaset_payload_z89e7xq0/ansible_community.mongodb.mongodb_replicaset_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_replicaset.py", line 459, in replicaset_add
fatal: [confsvr02-t01.dc01]: FAILED! => changed=false 
  invocation:
    module_args:
      arbiter_at_index: null
      auth_mechanism: null
      chaining_allowed: true
      connection_options: null
      debug: false
      election_timeout_millis: 10000
      force: false
      heartbeat_timeout_secs: 10
      login_database: admin
      login_host: 127.0.0.1
      login_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      login_port: 27017
      login_user: root
      max_time_ms: null
      members:
      - confsvr02-t01.dc01:27017
      - confsvr02-t02.dc05:27017
      - confsvr02-t03.dc06:27017
      protocol_version: 1
      reconfigure: false
      replica_set: csReplSet
      ssl: false
      ssl_ca_certs: null
      ssl_cert_reqs: CERT_REQUIRED
      ssl_certfile: null
      ssl_crlfile: null
      ssl_keyfile: null
      ssl_pem_passphrase: null
      validate: true
  msg: 'Unable to create replica_set: Some problem command replSetInitiate requires authentication, full error: {''ok'': 0.0, ''errmsg'': ''command replSetInitiate requires authentication'', ''code'': 13, ''codeName'': ''Unauthorized''} | OrderedDict([(''_id'', ''csReplSet''), (''protocolVersion'', 1), (''members'', [OrderedDict([(''_id'', 0), (''host'', ''confsvr02-t01.dc01:27017'')]), OrderedDict([(''_id'', 1), (''host'', ''confsvr02-t02.dc05:27017'')]), OrderedDict([(''_id'', 2), (''host'', ''confsvr02-t03.dc06:27017'')])]), (''settings'', {''chainingAllowed'': True, ''electionTimeoutMillis'': 10000})])'
```

Not sure if I'm missing something but from what I've seen in the sources, the authentication part is missing when trying to initialize a replicaset, except when SSL is enabled.

**Comment by rhysmeister** [comment]
Hello Paul,

Presumably you're converting a standalone replicaset to a 3 Member set? This process is supported by the module but it's a multi-step process. Background info...

https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/

Basically you should...

- Initiate the replicaset on the existing database.
- Add one new member (again with the mongodb_replicate module).
- Wait for the member to sync (the mongodb_status module can validate this).
- Add the final member.
- Wait for the member to sync.

I don't currently run this exact scenario in the CI but you can see examples of adding/removing members using the mongodb_replicaset module at https://github.com/ansible-collections/community.mongodb/tree/master/tests/integration/targets/mongodb_replicaset/tasks (See the files prefixed with 330).

Cheers,

Rhys

**Comment by qaoru** [comment]
Hi,

Thanks for the quick answer.
I'm not really trying to convert an existing rs, I'm using brand new nodes (it is basically mongo with a root user created). I was following steps described in https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/#deploy-new-replica-set-with-keyfile-access-control, where `rs.initiate()` is called with all nodes at once.
Is this behavior not supported ?

In the meantime, I'll try with the solution you described :smiley:

Regards,
Paul

**Comment by rhysmeister** [comment]
Hi Paul,

I'd assumed "existing database" meant a pre-existing single-node replicaset. So all members are 100% new? This should  work with a single module invocation. The scenario is in the CI. Note in the steps at...

https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/#deploy-new-replica-set-with-keyfile-access-control

They init the replicase first and then create the first user. If I remember correctly the rs.initiate() command will only work when there are no existing db files and creating a user will create new db files.

Cheers,

Rhys

**Comment by qaoru** [comment]
Hi,

I completely missed this "detail" as I was using docker images (with environment variables creating a user at startup).
Thanks for the help and the explanations / resources you provided !
