### ISSUE TITLE
Add support for pymongo 4+

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#424]
##### SUMMARY
pymongo 4+ is not currently supported because of the authenticate method used in the auth code. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_common.py

##### BACKGROUND LINKS

https://github.com/ansible-collections/community.mongodb/issues/423
https://github.com/ansible-collections/community.mongodb/pull/418

**Comment by rhysmeister** [comment]
```
# with good pwd
import pymongo
from pymongo import MongoClient
import urllib.parse
username = urllib.parse.quote_plus('admin')
password = urllib.parse.quote_plus('password')
MongoClient('mongodb://%s:%s@127.0.0.1' % (username, password))
c = MongoClient('mongodb://%s:%s@127.0.0.1' % (username, password))
c.get_database("admin").list_collections()
```

```
# with bad pwd
import pymongo
from pymongo import MongoClient
import urllib.parse
username = urllib.parse.quote_plus('admin')
password = urllib.parse.quote_plus('XXXXXXXXXXX')
MongoClient('mongodb://%s:%s@127.0.0.1' % (username, password))
c = MongoClient('mongodb://%s:%s@127.0.0.1' % (username, password))
c.get_database("admin").list_collections()   # <- This fails
```

Throws this error...

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/database.py", line 669, in list_collections
>     return self.__client._retryable_read(
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/mongo_client.py", line 1307, in _retryable_read
>     with self._secondaryok_for_server(read_pref, server, session) as (
>   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
>     return next(self.gen)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/mongo_client.py", line 1162, in _secondaryok_for_server
>     with self._get_socket(server, session) as sock_info:
>   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
>     return next(self.gen)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/mongo_client.py", line 1099, in _get_socket
>     with server.get_socket(
>   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
>     return next(self.gen)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/pool.py", line 1371, in get_socket
>     sock_info = self._get_socket(all_credentials)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/pool.py", line 1483, in _get_socket
>     sock_info = self.connect(all_credentials)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/pool.py", line 1337, in connect
>     sock_info.check_auth(all_credentials)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/pool.py", line 814, in check_auth
>     self.authenticate(credentials)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/pool.py", line 831, in authenticate
>     auth.authenticate(credentials, self)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/auth.py", line 548, in authenticate
>     auth_func(credentials, sock_info)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/auth.py", line 467, in _authenticate_default
>     return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-256')
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/auth.py", line 243, in _authenticate_scram
>     res = sock_info.command(source, cmd)
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/pool.py", line 719, in command
>     return command(self, dbname, spec, secondary_ok,
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/network.py", line 158, in command
>     helpers._check_command_response(
>   File "/Users/rhyscampbell/Library/Python/3.9/lib/python/site-packages/pymongo/helpers.py", line 170, in _check_command_response
>     raise OperationFailure(errmsg, code, response, max_wire_version)
> pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}

So we need to rewrite the auth code to catch this exception and then attempt auth if details have been provided. It's probably sensible to test the driver version and only use this new code for pymongo 4+. The old code can stay for now.

**Comment by zeitounator** [comment]
Just a friendly notification that there is [a question on devops.stackexchange.com][devops stackexchange question] about this issue which I answered.

I gave a couple of references to the repo, this issue and the [ongoing branch for pymongo4 compatibility][pymongo4 branch].

Thanks for all that work and good luck for a quick fix.

[devops stackexchange question]: https://devops.stackexchange.com/questions/15220
[pymongo4 branch]: https://github.com/ansible-collections/community.mongodb/tree/pymongo4

**Comment by rhysmeister** [comment]
Useful info: https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html

**Comment by rhysmeister** [comment]
Migrated to Pymongo 4. Code also tested against latest version of Pymongo 3 (3.12.3) and works.

https://github.com/ansible-collections/community.mongodb/pull/425

Dev release available at https://github.com/ansible-collections/community.mongodb/releases/tag/latest

**Comment by rhysmeister** [comment]
PyMongo4 requires that directConnection=True for listDatabases to function the way we need it to...

```
>>> from pymongo import MongoClient
>>> client = MongoClient(host="localhost", port=27017,  directConnection=True)
>>> client['admin'].command('listDatabases', 1.0)
{'databases': [], 'totalSize': 0.0, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1642451979, 1), 'signature': {'hash': b'\x8f|\xc3\x91}\xd5\xed\xbc \x07B\xc7\x91\x8f2~n\x122\xf9', 'keyId': 7054255196930572292}}, 'operationTime': Timestamp(1642451979, 1)}
>>> client = MongoClient(host="localhost", port=27017)
>>> client['admin'].command('listDatabases', 1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pymongo/database.py", line 598, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/database.py", line 504, in _command
    client=self.__client)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/pool.py", line 730, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/network.py", line 160, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/helpers.py", line 170, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: command listDatabases requires authentication, full error: {'operationTime': Timestamp(1642451989, 1), 'ok': 0.0, 'errmsg': 'command listDatabases requires authentication', 'code': 13, 'codeName': 'Unauthorized', '$clusterTime': {'clusterTime': Timestamp(1642451989, 1), 'signature': {'hash': b'}W\xc2\x9e\xf8\x8f\xf2\x1e\xe4\x96s\x1c9\xec\xd7\x99\x08\x0f\x07t', 'keyId': 7054255196930572292}}}
>>> client = MongoClient(host="localhost", port=27017, directConnection=True)
>>> client['admin'].command('listDatabases', 1.0)
{'databases': [], 'totalSize': 0.0, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1642453279, 1), 'signature': {'hash': b'\xa0e.\xfb\x06\xfc\xa3u\x17\xa0\x8es\x99\xa2p\x98\xb8\xbb;f', 'keyId': 7054255196930572292}}, 'operationTime': Timestamp(1642453279, 1)}
```

**Comment by rhysmeister** [comment]
FInal changes for this merged in https://github.com/ansible-collections/community.mongodb/pull/433

CI includes tests running on pymongo 4 and pymongo 3.14.*
