### ISSUE TITLE
SSL options disabled in mongodb_shell module

### ISSUE THREAD

**Issue by jaykay321** [ansible-collections/community.mongodb#430]
Hi,
I'm kinda newbie when it comes to github, so please don't be mad at me for not posting this issue on stackoverflow rather than github. I just wanted an answer from the source.  I am trying to use community.mongodb.mongodb_shell module in one of my own roles, but one thing just doesn't make sense to me. Why this module in comparison to other modules like mongodb_user does not use SSL options? Will there be any issues when I try to use it on instance where SSL is required?

https://github.com/ansible-collections/community.mongodb/blob/26c77072ff10a2a396ee309928d052c142811c7a/plugins/modules/mongodb_shell.py#L291

**Comment by rhysmeister** [comment]
Hello,

Most of the module uses the pymongo api while the mongodb_shell module interacts with command-line tools, i.e. mongo or mongosh. You can probably use the additional_args parameter of the mongodb_shell module to pass ssl connection options.

Rhys

**Comment by jaykay321** [comment]
Thank you for answer Rhys. I tried to do it with a simple playbook:

`---
- name: Test mongoshell
  hosts: localhost

  tasks:
  - name: Test mongoshell connection
    community.mongodb.mongodb_shell:
      login_host: 'mongodb://mongodb-1.example.com,mongodb-2.example.com,mongodb-3.example.com/?replicaSet=rs0'
      login_user: root
      login_password: passw0rd
      login_database: admin
      eval: "db.getRoles({showBuiltinRoles: true})"
      additional_args:
        tls: yes
        tlsCertificateKeyFile: test-client1.pem
        tlsCAFile: test-ca.pem`
        
It essentially look ok, but there is something odd with parsing the login_host param. I receive following error message:

> fatal: [localhost]: FAILED! => {"changed": false, "msg": "exception: '/mongodb-1.example.com:27017' in 'mongodb://%2Fmongodb-1.example.com:27017,mongodb-2.example.com:27017,mongodb-3.example.com%2F%3FreplicaSet%3Drs0:27017/test?replicaSet=mongodb%3A' appears to be a unix socket, but does not end in '.sock'\nexiting with code 1"}

**Comment by rhysmeister** [comment]
Hello @jaykay321,

If you look in the error we can see the encoded version of '/' %2F. I've never tested these style of connection strings but I guess there's some form of shell escaping happening somewhere. At the moment I'm not sure where. 

Can you try it again with the debug parameter to true? This should give us the command that is actually attempted. I attempted a fix with your url format but then it complain about ReadPreference=nearest could not be satisfied. I then attempted to get around this by adding the ReadPreference to the url but there seems to be a bug in the mongo shell preventing that approach...

https://jira.mongodb.org/browse/SERVER-39222 (Quite old and apparently not fixed)

I'm working on a fix over at https://github.com/ansible-collections/community.mongodb/pull/431

I've introduced a new module parameter to omit certain mongo options from the command...

```
  - name: Test mongoshell connection
    community.mongodb.mongodb_shell:
      login_host: 'localhost:3001,localhost:3002,localhost:3003'
      login_user: "{{ mongodb_admin_user }}"
      login_password: "{{ mongodb_admin_password }}"
      login_database: admin
      eval: "db.getRoles({showBuiltinRoles: true})"
      mongo_cmd: "{{ mongo_cmd }}"
      debug: yes
      omit:
        - "port"
```

Not the format of login host. I'm pretty sure this still connects to the replicaset (it will auto-discover the name) so this should do what you want.

**Comment by jaykay321** [comment]
Here's the result of playbook with debug enabled
```
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "mongo test --host mongodb://mongodb-1.example.com,mongodb-2.example.com,mongodb-3.example.com/?replicaSet=rs0 --port 27017 --username root --password ******** --authenticationDatabase admin --eval 'db.getRoles({showBuiltinRoles: true})' --quiet  --tls  --tlsCertificateKeyFile test-client1.pem  --tlsCAFile test-ca.pem", "err": "", "msg": "exception: '/mongodb-1.example.com:27017' in 'mongodb://%2Fmongodb-1.example.com:27017,mongodb-2.example.com:27017,mongodb-3.example.com%2F%3FreplicaSet%3Drs0:27017/test?replicaSet=mongodb%3A' appears to be a unix socket, but does not end in '.sock'\nexiting with code 1", "out": "exception: '/mongodb-1.example.com:27017' in 'mongodb://%2Fmongodb-1.example.com:27017,mongodb-2.example.com:27017,mongodb-3.example.com%2F%3FreplicaSet%3Drs0:27017/test?replicaSet=mongodb%3A' appears to be a unix socket, but does not end in '.sock'\nexiting with code 1\n", "rc": 1
```
I've tried the omit parameter but it's not recognized by Ansible.

When I replaced the connection string with the one you posted it started to work properly :)
here's a proper playbook code:

```
---
- name: Test mongoshell
  hosts: localhost

  tasks:
  - name: Test mongoshell connection
    community.mongodb.mongodb_shell:
      login_host: 'mongodb-1.example.com,mongodb-2.example.com,mongodb-3.example.com'
      login_port: 27017
      login_user: root
      login_password: passw0rd
      login_database: admin
      eval: "db.getRoles({showBuiltinRoles: true})"
      debug: yes
      additional_args:
        tls: yes
        tlsCertificateKeyFile: test-client1.pem
        tlsCAFile: test-ca.pem
    register: result

  - name: Show results
    debug:
      msg: "{{ result }}"
```
One more question. How does the pymongo or your module recognize that given host names are in replica set?

Thank You so much for help Rhys :)

**Comment by rhysmeister** [comment]
@jaykay321,

No problem. 

"module recognize that given host names are in replica set?" - Basically I don't. I dpeend on the mongo shell to do that in that case. In the case of pymongo that's just build in. The driver will discover the replicaset. You actually have to turn that off if you don't want it.

Cheers,

Rhys

**Comment by rhysmeister** [comment]
I've merged a change with the omit feature to dev...

https://github.com/ansible-collections/community.mongodb/pull/431

You don't need to worry about this, since you're running on the default port, but it could be useful for those running on non-standard and diverse ports. This seems to be a good enough of a solution so closing.

Cheers,

Rhys

**Comment by jaykay321** [comment]
Thank You Rhys :)
