### ISSUE TITLE
mongodb_shell: check_mode is not supported

### ISSUE THREAD

**Issue by brsysadmin** [ansible-collections/community.mongodb#478]
##### SUMMARY

Maybe I'm wrong but I have the feeling the module mongodb_shell is not compatible with the Ansible's check_mode.
Example: if I execute my playbook with --diff --check arguments, the mongodb_shell action is really executed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
community.mongodb.mongodb_shell
```

##### ANSIBLE VERSION

```
# ansible --version
ansible [core 2.12.6]
  config file = /etc/ansible.cfg
  configured module search path = ['/home/sysadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/sysadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
  ```

##### COLLECTION VERSION

```
# ansible-galaxy collection list community.mongodb

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.4.0
```

##### CONFIGURATION

```
# ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

##### STEPS TO REPRODUCE

Create a playbook looks like:

```
- hosts:
    - "all"
  become: "yes"
  become_user: "root"
  connection: "ssh"
  gather_facts: True
  tasks:
    - name: "Execute a JS script"
      community.mongodb.mongodb_shell:
        db: "myDb"
        debug: "no"
        file: "/tmp/myExampleScript.js"
        login_database: "admin"
        login_host: "localhost"
        login_password: "admin"
        login_port: "p@ssw0rd"
        login_user: "admin"
```

Create a file /tmp/myExampleScript.js on the remote machine:

```
db.createCollection("myCollection");
```

Execute the playbook:

```
# ansible-playbook --limit server1 --diff --check
```

##### EXPECTED RESULTS

In check mode the module should say "OK" or "CHANGED" but should execute nothing.

##### ACTUAL RESULTS

The command is really executed no matter if --check is present or absent on the command line.

**Comment by rhysmeister** [comment]
Hello @brsysadmin,

supports_check_mode is set to true ffor this module and it shouldn't be. There's no real reliable way of checking this anyway. I'll fix it.

Cheers,

Rhys

**Comment by rhysmeister** [comment]
Fixed in https://github.com/ansible-collections/community.mongodb/pull/479

**Comment by brsysadmin** [comment]
Thank you for the fix 👍 

I tested changing the value on my side: the behavior is better :)

But with supports_check_mode = False, now the task is considered _skipping_ when the playbook is executed with _--check_.
It is better yes BUT, from my point of view, it is dangerous because the check mode and the real mode are different. I mean, the user see _skipping_ when in reality something will be executed :)

Maybe it could be better to patch the code to get this behavior:
  - if _--check_ is present:
    - in reality, the command is not executed
    - but the variable _result['changed']_ is setted to _True_ to force the Ansible output to say "hey there is a changed"

What do you think? :)

**Comment by rhysmeister** [comment]
This is how the ansible shell and command modules work and I'm mindful not to deviate from this. You can probably acheive what you want with a combination of changed_when and the ansible_check_mode variable.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#defining-changed
https://docs.ansible.com/ansible/2.3/playbooks_checkmode.html

**Comment by brsysadmin** [comment]
No problem I understand :)

Thank you for your answers
