### ISSUE TITLE
Create worklow to build and publish a collection

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#50]
##### SUMMARY

It sould be possible to create a workflow that can build and deploy a collection to Ansible Galaxy. This could perhaps be triggered by a keyword in the commit message. 

##### ISSUE TYPE
- Feature Idea

**Comment by gundalow** [comment]
Hi, we can provide this. Which will be based on Git Tag.

**Comment by rhysmeister** [comment]
Sounds good.

Quick question: Do you know if the following procedure to generate documentation will work with the new project structure? 

https://docs.ansible.com/ansible/2.5/dev_guide/developing_modules_documenting.html#testing-documentation

I have a workflow to generate documentation and I'd like to incorporate it if possible.
