### ISSUE TITLE
How to run the initial cluster configuration？

### ISSUE THREAD

**Issue by z3473** [ansible-collections/community.mongodb#507]
[root@localhost mongodb]# ansible-test integration --docker default -v --color --python 3.9 mongodb_shard
Configured locale: en_US.UTF-8
FATAL: Cannot run integration tests without "roles/test/" or "tests/integration/targets/".
(venv) [root@localhost mongodb]# ansible-test integration --docker default -v --color --python 3.9 mongodb_status
Configured locale: en_US.UTF-8
FATAL: Cannot run integration tests without "roles/test/" or "tests/integration/targets/".
(venv) [root@localhost mongodb]# 

How to run the initial cluster configuration？
These modules are only useful for replicaset (or sharded) MongoDB clusters:

community.mongodb.mongodb_maintenance: Enables or disables [maintenance](https://docs.mongodb.com/manual/reference/command/replSetMaintenance/) mode for a secondary member.
community.mongodb.mongodb_replicaset: Initialises a MongoDB replicaset.
community.mongodb.mongodb_status: Validates the status of the replicaset.
community.mongodb.mongodb_stepdown: [Step down](https://docs.mongodb.com/manual/reference/command/replSetStepDown/) the MongoDB node from a PRIMARY state.

**Comment by rhysmeister** [comment]
There's a section dealing with running the integration tests in the readme...

https://github.com/ansible-collections/community.mongodb#running-the-integration-and-unit-tests

Note that there's a specific directory structure required.

From the error above I would guess that you might night be in the correct directory. You should be in the root of the repo and you should be able to `ls tests/integration/targets/`.
