### ISSUE TITLE
How do you define the hosts of inventory in ansible?

### ISSUE THREAD

**Issue by z3473** [ansible-collections/community.mongodb#509]
For example:
[mongo]
#192.168.2.113
192.168.2.114
192.168.2.115
192.168.2.116

**Comment by rhysmeister** [comment]
Hello @z3473,

Best to check the manual for stuff like this... https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

**Comment by z3473** [comment]
May I ask what instant messenger you use, I need your help. Thanks!

**Comment by z3473** [comment]
May I ask what instant messenger you use, I need your help. Thanks!
