### ISSUE TITLE
Rename repo to community.mongodb

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.mongodb#52]
##### SUMMARY
Hi,
To be more consistent with the other repos https://github.com/ansible-collections/ I'd like to rename this GitHub Repo to be `community.mongodb`

* Old URLs for issues and PRs will still work
* Old git URLs will work, though it will be good to update them locally
* We will need to update the URLs in `galaxy.yml`

Are you happy with this?
##### ISSUE TYPE
- Bug Report

**Comment by rhysmeister** [comment]
Yes, all good.
