### ISSUE TITLE
Support multiple bind ip addresses

### ISSUE THREAD

**Issue by pvanagtmaal** [ansible-collections/community.mongodb#522]
##### SUMMARY
MongoDB supports binding to multiple ip addresses, or even a mix of both sockets and ip addresses. This collection however only supports either an ip address or a socket.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.mongodb.mongod, maybe more

##### ADDITIONAL INFORMATION

If you try to follow the syntax from the link below, for example the community.mongodb.mongod role fails on waiting for the port to become available because it doesn't split the provided list

[docs](https://www.mongodb.com/docs/v4.4/reference/configuration-options/#mongodb-setting-net.bindIp)

specifying
```yaml
bind_ip: "{{ mongodb_bind_ips | join(',') }}"
```

currently results in:

```
RUNNING HANDLER [community.mongodb.mongodb_mongod : Restart mongod] **************************************************************************************************************************
changed: [ansible_host]

RUNNING HANDLER [community.mongodb.mongodb_mongod : Wait for port to become active] **********************************************************************************************************
fatal: [ansible_host]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 127.0.0.1,1.2.3.4:27017"}
```

However, the server itself runs fine:

```
# ss -tlpn | grep 27017
LISTEN 0      4096                                   127.0.0.1:27017      0.0.0.0:*    users:(("mongod",pid=1310586,fd=15))
LISTEN 0      4096                                   1.2.3.4:27017         0.0.0.0:*    users:(("mongod",pid=1310586,fd=14))
```

**Comment by rhysmeister** [comment]
According to this post the syntax you are using isn't quite right...

https://stackoverflow.com/questions/29109134/how-to-set-mongod-conf-bind-ip-with-multiple-ip-address

Earlier version of MongoDB used a Python style list format...

[172.31.60.184,127.0.0.1]

And new versions seem to require a semi-colon as a seperator...

127.0.0.1;192.168.1.0 

You can also consider setting bind_ip_all to true

**Comment by pvanagtmaal** [comment]
As I noted, it does work for mongodb itself, but the mongod role from this collection cannot handle the ip string because it waits for the full string + port combination (e.g. 127.0.0.1,1.2.3.4:27017 instead of either or both combinations, i.e. 127.0.0.1:27017 and 1.2.3.4:27017).

The syntax varies across stackoverflow, but the MongoDB documentation for both 4.4 and 6.0 point to a comma separated list:

(4.4)[https://www.mongodb.com/docs/v4.4/core/security-mongodb-configuration/]
(6.0)[https://www.mongodb.com/docs/v6.0/core/security-mongodb-configuration/]

I'm reluctant to go with 0.0.0.0 as bind_ip because I only want the loopback and vpn interfaces, not the public facing interface. For now I'll use a proxy.

**Comment by rhysmeister** [comment]
It's not the collection. It just writes whatever you give it. I've managed to get it to work with the following...

```
net:
  port: 27017
  bindIp: "127.0.0.1,172.18.0.2"
```
Basically the values for BindIp must be quoted. There are loads of reports of funny behavoiur..

https://jira.mongodb.org/browse/DOCS-10931

Maybe this is something to do with the underlaying yaml library? Anyway, not really an issue with the role itself IMHO.

Rhys

**Comment by rhysmeister** [comment]
Not a big. Closing...

**Comment by rhysmeister** [comment]
Added your suggestion in https://github.com/ansible-collections/community.mongodb/pull/528
