### ISSUE TITLE
mongodb_auth: error on pyyaml install

### ISSUE THREAD

**Issue by LeoSpyke** [ansible-collections/community.mongodb#523]
##### SUMMARY
I get an error while configuring an Amazon Linux 2 instance.
The problem occurs when the playbook tries to install the `pyyaml_package` (variable which defaults to python3-yaml), where the package simply does not exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`mongodb_auth` role

##### ANSIBLE VERSION
```
ansible [core 2.14.1]
  config file = None
  configured module search path = ['REDACTED', '/usr/share/ansible/plugins/modules']
  ansible python module location = REDACTED
  ansible collection location = REDACTED
  executable location = REDACTED
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# REDACTED
Collection        Version
----------------- -------
community.general 6.1.0

# REDACTED
Collection        Version
----------------- -------
community.general 6.1.0
```

##### OS / ENVIRONMENT
EC2 instance on AWS with Amazon Linux 2

##### STEPS TO REPRODUCE
Simple playbook execution on a fleet of servers, the tasks/roles execution order is the following:
1. role mongodb_repository
2. role mongodb_install
3. role mongodb_mongod
4. community.mongodb.mongodb_replicaset (for the replica set creation)
5. role mongodb_auth

I'm willing to fix it if needed.

Thank you.

**Comment by rhysmeister** [comment]
Hello @LeoSpyke 

You can probably work around this by adding a file called Amazon.yml to the vars folder of the mongodb_auth role. 

Rhys
