### ISSUE TITLE
Ubuntu support for role mongodb_linux

### ISSUE THREAD

**Issue by french-kiwy** [ansible-collections/community.mongodb#542]
I think there's a small issue with the way Debian distro are managed in role mongodb_linux.
file `https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_linux/vars/Debian.yml`   should contains :
```
---
# Packages for Debian distros
ntp_package: systemd-timesyncd
ntp_service: systemd-timesyncd
gnu_c_lib: libc6
```  
I'm still learning but there might be also an error there because [Debian is actually using this as a sync time service](https://wiki.debian.org/NTP) and [timesync is capable of synchronizing with ntp server](https://www.freedesktop.org/software/systemd/man/systemd-timesyncd.service.html) so maybe the whole file should be using those value instead of ntp which is an additional package to install.  
I willing to do start pushing in the repo but I have know idea how integration test and all works so it may take a while.

**Comment by rhysmeister** [comment]
Hello @french-kiwy,

Is this related to a specific version of Ubuntu/Debian. I'm actually just in the process of adding Bullseye to the CI and I haven't seen this yet.

Rhys

**Comment by french-kiwy** [comment]
Well I don't know from what I can read Ubuntu 18.04 already is using timesyncd as basic time sync service.
I don't know about debian and less aware about this one but if Ubuntu 18.04 is already using timesyncd I suppose this is the case for older debian as well.
