### ISSUE TITLE
Confuse about documentation and roles

### ISSUE THREAD

**Issue by french-kiwy** [ansible-collections/community.mongodb#551]
Hello,
Maybe I'm a bit confuse about how things are suppose to wor, I'm trying to deploy a simple 3 node cluster with a replica_set.

I found multiple example on how this could be possible but it seems like example or documentation is not up to date. 
For role [mongodb_mongod](https://github.com/ansible-collections/community.mongodb/tree/master/roles/mongodb_mongod) Which is :  

> A simple role to aid in the setup of a MongoDB replicaset.

the documentation mention admin login and password but those value are never used in the code of the role or I cannot find it at least.  

In [mongodb_auth](https://github.com/ansible-collections/community.mongodb/tree/master/roles/mongodb_auth) I found the only likely example possible to deploy a full replica set however it seems to not work or at least I wasn't able to run it.  I always end up with a cluster that is not havin the proper replicaset name or impossible to authenticate or something.   And this example seems to imply that mongodb_mongod do not initialize the replica_set on its own which is troubling as it seems to be a role for doing that.

I don't know if I misunderstand, I'm very much a beginner in mongodb installation and a recent ansible user but this seems a bit confuse to me how I can use those role to deploy something.  

I hope you'll not take it badly I'm just very confuse with the documentation.  Maybe having an example folder at the root with all example possible would be nice and makes it easier to get started.

**Comment by rhysmeister** [comment]
Hello @french-kiwy;

The documentation for most of these roles is limited to that role only. For example the mongodb_mongod simple *prepares* the nodes by installing software. You still need to init the replicaset and create users etc. The variables are provided there as a default, mostly for testing, but also for you to use in your playbook after importing the role. The examples in the roles are not meant to be a full guide to cluster deployment. 

For full examples you could look at

- https://github.com/rhysmeister/AutomatingMongoDBWithAnsible (no longer maintained)
- https://github.com/superset1/Ansible_role_mongodb
- https://github.com/ansible-collections/community.mongodb/tree/master/roles/<role name>/molecule (some full example that we use in our testing)

The MongoDB Docs are good for seeing what is required...

https://www.mongodb.com/docs/manual/tutorial/deploy-replica-set/

If you're having specific problems with a role, please provide the Playbook you are running, as well as any error message you recieve.

Cheers,

RHys

**Comment by french-kiwy** [comment]
That's super nice to have clarification thank you very much.
Maybe having a readme for roles that shows test and production variable would help other lost folks like me in the futur. 
But thank you for all the links.
Cheers
