### ISSUE TITLE
mongod role impossible to use ?

### ISSUE THREAD

**Issue by french-kiwy** [ansible-collections/community.mongodb#552]
trying to use the role mongodb_mongod I think the configuration file is impossible to use in the current state.  
According to [documentation](https://www.mongodb.com/docs/manual/tutorial/enforce-keyfile-access-control-in-existing-replica-set/) if you want to deploy a replica set with a key file you first need to initialise the replica then create users.   
In `mongod.conf` it means that security should be before user are created :  
```
security:
  authorization: disabled
  keyFile: /etc/keyfile
```

but the template [mongod.yml.j2](https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_mongod/templates/mongod.conf.j2) is written like this :  

```
{% if authorization == "enabled" %}
security:
  authorization: {{ authorization }}
{% if replicaset or sharding %}
  keyFile: {{ openssl_keyfile_path }}
{% endif %}
{% endif %}
```

Which means that you need to have authorization to enabled to actually put a keyfile configuration.  
If the goal of the role is to prepare to setup a replica set it should be more like this : 

```
security:
{% if authorization == "enabled" %}
  authorization: {{ authorization }}
{% endif %}
{% if replicaset or sharding %}
  keyFile: {{ openssl_keyfile_path }}
{% endif %}
```

By the way thank you for the great help you've provided so far.

**Comment by rhysmeister** [comment]
Hello @french-kiwy,

We've written extensive tests for all of our Ansioble roles (and modules) and we're therefore pretty confident they work. For example note this Molecule test for mongodb_mongod...

https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_mongod/molecule/default/playbook.yml

We verifiy that the replicaset has been successfully setup with the following TestInfra tests...

https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_mongod/molecule/default/tests/test_default.py

These tests are execute daily in our CI and we aim to fix any problems quickly. A recent successful run can be seen here...

https://github.com/ansible-collections/community.mongodb/actions/runs/4361649625/jobs/7625734490

You can read mnore about Molecule here (I really like it)... https://molecule.readthedocs.io/en/latest/

Note that the localhost exception allows you to create the first user in MongoDB with access control enabled... https://www.mongodb.com/docs/manual/core/localhost-exception/

Cheers,

Rhys

**Comment by french-kiwy** [comment]
I found my mistake and it's on me I didn't want to install pip package on my server and tried to setup a replica_set from outside the server but you can only do that from 127.0.0.1.
the more you know.
Thank you for you great support.
Cheers

**Comment by rhysmeister** [comment]
@french-kiwy  - it will work from outside the server, see login_host. You'll probably need to use this in conjunction with delegate_to and run_once... https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_delegation.html
