### ISSUE TITLE
Alma Linux 8 - mongodb_install specific version installation is broken

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#555]
##### SUMMARY

Installing a specific version in AL8 is broken...

https://github.com/ansible-collections/community.mongodb/actions/runs/4398887442/jobs/7703047624

`fatal: [almalinux_8]: FAILED! => {"attempts": 5, "changed": false, "failures": ["No package mongodb-org*6.0.3 available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}`

Seems broken in yum/dnf. I've tried in a docker container with the command directly.

```
[xxx@almalinux_8 /]# yum search 'mongodb-org*6.0.3'
Last metadata expiration check: 2:35:20 ago on Sun Mar 12 16:35:31 2023.
No matches found.

```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_install

**Comment by tchandelle** [comment]
Might be fixed by #601

**Comment by rhysmeister** [comment]
@tchandelle Indeed it does! https://github.com/ansible-collections/community.mongodb/pull/602

Thank you.

**Comment by tchandelle** [comment]
@rhysmeister Any idea when a new tag version will be released with this fix? Thanks

**Comment by rhysmeister** [comment]
@tchandelle It's on my list. Shouldn't be too long.

**Comment by rhysmeister** [comment]
@tchandelle Done: https://github.com/ansible-collections/community.mongodb/pull/604
