### ISSUE TITLE
Set the mongoDB configuration file ("/etc/mongodb.conf") to variable

### ISSUE THREAD

**Issue by jerome-licciardello** [ansible-collections/community.mongodb#580]
##### SUMMARY

In order to test in localhost (on a single server), a replica set of 3 nodes or a sharded cluster of at least 1 shard, is it possible to set the MongoDB configuration file "/etc/mongod.conf" as a variable, please?

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

In order to test in localhost (on a single server), a replica set of 3 nodes or a sharded cluster of at least 1 shard, is it possible to set the MongoDB configuration file "/etc/mongod.conf" as a variable, please?

```yaml

```

**Comment by rhysmeister** [comment]
Hello @jerome-licciardello,

This type of thing is outside the scope of the roles really. You could acheive this yourself with `mongod -f /path/to/config.cfg` https://www.mongodb.com/docs/manual/reference/program/mongod/#std-option-mongod.--config

Cheers,

Rhys

**Comment by rhysmeister** [comment]
No further feedback. Closing.
