### ISSUE TITLE
Add support for MongoDB Atlas

### ISSUE THREAD

**Issue by schurzi** [ansible-collections/community.mongodb#587]
##### SUMMARY
Atlas is the DBaaS version of MongoDB (see: https://www.mongodb.com/atlas/database). Some of the existing modules in this collection can be used to interact with Atlas instances, but it is missing modules to create and manage the Atlas instances themselves. 

Some time ago I created a collection with the basic features that are required to manage Atlas instances (see: https://github.com/T-Systems-MMS/ansible-collection-mongodb-atlas). I want to offer to transfer the modules to this community collection to better aggreate MongoDB features in Ansible. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
new modules `atlas_cluster`, `atlas_user`, `atlas_ldap_user`, `atlas_whitelist` and possibly more

##### ADDITIONAL INFORMATION
I am willing (and would be pleased) to keep maintaining the Atlas functionality in this collection!

**Comment by rhysmeister** [comment]
Hi @schurzi,

Great idea. Feel free to create a PR.

Rhys
