### ISSUE TITLE
Creating/updating a role fails if only one of the clientSource or serverAddress values is specified in authenticationRestrictions

### ISSUE THREAD

**Issue by dorancemc** [ansible-collections/community.mongodb#610]
##### SUMMARY
When using the community.mongodb.mongodb_role module, execution fails if the values of authenticationRestrictions are changed. It only fails if a role is created with values in authenticationRestriction where only one of the clientSource or serverAddress values is specified; if there is no data or the both valuers are present, the module does not fail. This is because the current module reads the current values of clientSource and serverAddress, but if only one value is present, the module fails to execute.

to avoid this error, lines [306 and 307](https://github.com/ansible-collections/community.mongodb/blob/upgrade_actions/plugins/modules/mongodb_role.py#L306-L307) should be replaced with 
```
                sorted(reformat_authenticationRestrictions, key=lambda x: (x.get('clientSource', ''), x.get('serverAddress', ''))) !=
                sorted(authenticationRestrictions, key=lambda x: (x.get('clientSource', ''), x.get('serverAddress', ''))) or
```                

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/modules/mongodb_role.py

##### ANSIBLE VERSION
```
ansible --version
ansible [core 2.15.5]
  config file = None
  python version = 3.9.6 (default, Aug 11 2023, 19:44:49) [Clang 15.0.0 (clang-1500.0.40.1)] 
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
ansible-galaxy collection list community.mongodb
community.mongodb             1.6.3  
```

##### OS / ENVIRONMENT
Ubuntu 20.04.6 LTS
mongodb_version: 6.0.9

##### STEPS TO REPRODUCE

running a playbook with the following role definition
```yaml
  - name: monitoring
    roles:
      - db: admin
        role: clusterMonitor
      - db: admin
        role: readAnyDatabase
    authenticationRestrictions:
      - clientSource: "{{ monitoring_ips }}"
``` 

```
    Traceback (most recent call last):
      File "/tmp/ansible_community.mongodb.mongodb_role_payload_8qvs_x20/ansible_community.mongodb.mongodb_role_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_role.py", line 367, in main
      File "/tmp/ansible_community.mongodb.mongodb_role_payload_8qvs_x20/ansible_community.mongodb.mongodb_role_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_role.py", line 306, in check_if_role_changed
      File "/tmp/ansible_community.mongodb.mongodb_role_payload_8qvs_x20/ansible_community.mongodb.mongodb_role_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_role.py", line 306, in <lambda>
    KeyError: 'serverAddress'
```

If in the definition I give an empty list for serverAddress the client can not connect to the database, because an empty list is created for serverAddress and according to the MongoDB documentation "If present, the server will verify that the client's connection was accepted via an IP address in the given list." [authentication-restrictions](https://www.mongodb.com/docs/manual/reference/method/db.createUser/#authentication-restrictions)

**Comment by rhysmeister** [comment]
@dorancemc Closing this issue as your fix was merged.
