### ISSUE TITLE
mongodb_auth leaves leftovers after uninstalling MongoDB

### ISSUE THREAD

**Issue by mikkolaj** [ansible-collections/community.mongodb#646]
##### SUMMARY

`mongodb_auth` role creates a file outside of default MongoDB installation directories that the official [uninstall guide](https://www.mongodb.com/resources/products/fundamentals/uninstall-mongodb) suggests to remove. Consequently, user is required to remove the `/root/mongodb_admin.success` manually before setting up the auth with `mongodb_auth` on a fresh MongoDB installation once more.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`mongodb_auth` role

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.2]
  config file = /home/mikolaj/IdeaProjects/dslam-ansible/vagrant/observability/ansible.cfg
  configured module search path = ['/home/mikolaj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mikolaj/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mikolaj/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mikolaj/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /home/mikolaj/.local/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.mongodb 1.6.3
```

##### CONFIGURATION

```
CONFIG_FILE() = None
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

`Ubuntu 22.04.4 LTS`

##### STEPS TO REPRODUCE

1. Install MongoDB 6.0.15 in a preferred way
2. Set up auth with `mongodb_auth` role (play pasted below)
3. Uninstall MongoDB by following the official [uninstall guide](https://www.mongodb.com/resources/products/fundamentals/uninstall-mongodb)
4. Install MongoDB again
5. Try to set up auth with `mongodb_auth` role

```yaml
- name: Setup auth
  hosts: mongo
  become: true
  roles:
    - role: community.mongodb.mongodb_auth
```

##### EXPECTED RESULTS

It should be possible to reinstall mongo and set up the auth without worrying about the `/root/mongodb_admin.success` file.

##### ACTUAL RESULTS

Auth is enabled but no admin user is created. It's impossible to connect to MongoDB as the admin user.

```paste below
TASK [community.mongodb.mongodb_auth : Add mongo admin user with localhost exception] *************************************************************************************************************************************
skipping: [mongo]
```
##### POSSIBLE SOLUTIONS
 - moving the file under `/var/lib/mongodb` - breaks backwards compatibility if no additional logic is added (can be handled with some effort), transparent to a new user
 - exposing a way for the user to override the file location with role variable - no backwards compatibility issues, but requires user to configure it consciously

**Comment by mikkolaj** [comment]
Hello! Once we confirm it should be fixed, I'm willing to implement a solution. Waiting to hear your take on the issue.

**Comment by rhysmeister** [comment]
Hello @mikkolaj,

There's a note in the role readme about the reverse case of touching the file when role begins to manage an existing server with an admin user... https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_auth/README.md. We use this type of pseudo-idempotency in a few places in this collection.

I would just add a note about the reverse case. I'd say it's best practice to restage the OS rather than reusing an old installation. Mostly these roles/modules are intended to deal with new deployments and assume fresh hosts.

Still, add a "fix" if you want. I don't think the role should touch anything under the datadir. Perhaps an override, as you mention, is best.

Cheers,

Rhys

**Comment by mikkolaj** [comment]
Ok, this assumption of dealing with fresh hosts changes things.

I've been successfully using this collection to test things out manually on old installations, so I thought that this step of deleting the file could be abstracted away from the user. Now I see that it probably doesn't matter that much.

Still, I would like to add an override for the file's location and a more precise description of it's purpose in the README.

Thanks,
Mikołaj
