### ISSUE TITLE
Simple Playbook for running mongodb sharded cluster ?

### ISSUE THREAD

**Issue by cemakpolat** [ansible-collections/community.mongodb#680]
Hi, 
I was looking for a ready to use simple playbook to run mongodb sharded cluster along with mongodb exporter. Do you have already test yamls to build such an environment? 

BR
Cem

**Comment by rhysmeister** [comment]
Hello @cemakpolat,

See the "Usage Examples" section in the readme - https://github.com/ansible-collections/community.mongodb?tab=readme-ov-file#usage-examples

Rhys
