### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.mongodb#7]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/community.mongo against this repo

##### ISSUE TYPE
- Bug Report

**Comment by gundalow** [comment]
Clarification:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

**Comment by rhysmeister** [comment]
There have been no commits to the master branch of the MongoDB collection since it was created so we should be able to pull most of these changes across. I'm pretty sure there were a few commits for the mongodb lookup plugin that don't seem to be here. I'll check that out once I've merged changed for the below.

`diff -qr mongodb/plugins/ community.mongo/plugins/`

> Only in mongodb/plugins/modules: __pycache__
> Only in community.mongo/plugins/modules: mongodb_info.py
> Files mongodb/plugins/modules/mongodb_parameter.py and community.mongo/plugins/modules/mongodb_parameter.py differ
> Files mongodb/plugins/modules/mongodb_replicaset.py and community.mongo/plugins/modules/mongodb_replicaset.py differ
> Files mongodb/plugins/modules/mongodb_shard.py and community.mongo/plugins/modules/mongodb_shard.py differ
> Files mongodb/plugins/modules/mongodb_user.py and community.mongo/plugins/modules/mongodb_user.py differ

`diff -qr mongodb/tests/ community.mongo/tests/`

> Only in mongodb/tests/: coverage.sh
> Only in community.mongo/tests/integration/targets: mongodb_info
> Files mongodb/tests/integration/targets/mongodb_parameter/defaults/main.yml and community.mongo/tests/integration/targets/mongodb_parameter/defaults/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_parameter/meta/main.yml and community.mongo/tests/integration/targets/mongodb_parameter/meta/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_parameter/tasks/mongod_singlenode.yml and community.mongo/tests/integration/targets/mongodb_parameter/tasks/mongod_singlenode.yml differ
> Files mongodb/tests/integration/targets/mongodb_replicaset/defaults/main.yml and community.mongo/tests/integration/targets/mongodb_replicaset/defaults/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_replicaset/meta/main.yml and community.mongo/tests/integration/targets/mongodb_replicaset/meta/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_replicaset/tasks/main.yml and community.mongo/tests/integration/targets/mongodb_replicaset/tasks/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_replicaset/tasks/mongod_replicaset.yml and community.mongo/tests/integration/targets/mongodb_replicaset/tasks/mongod_replicaset.yml differ
> Files mongodb/tests/integration/targets/mongodb_shard/defaults/main.yml and community.mongo/tests/integration/targets/mongodb_shard/defaults/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_shard/meta/main.yml and community.mongo/tests/integration/targets/mongodb_shard/meta/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_shard/tasks/main.yml and community.mongo/tests/integration/targets/mongodb_shard/tasks/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_shard/tasks/mongod_replicaset.yml and community.mongo/tests/integration/targets/mongodb_shard/tasks/mongod_replicaset.yml differ
> Files mongodb/tests/integration/targets/mongodb_user/defaults/main.yml and community.mongo/tests/integration/targets/mongodb_user/defaults/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_user/meta/main.yml and community.mongo/tests/integration/targets/mongodb_user/meta/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_user/tasks/main.yml and community.mongo/tests/integration/targets/mongodb_user/tasks/main.yml differ
> Files mongodb/tests/integration/targets/mongodb_user/tasks/mongod_replicaset.yml and community.mongo/tests/integration/targets/mongodb_user/tasks/mongod_replicaset.yml differ
> Files mongodb/tests/integration/targets/setup_mongodb/defaults/main.yml and community.mongo/tests/integration/targets/setup_mongodb/defaults/main.yml differ
> Files mongodb/tests/integration/targets/setup_mongodb/handlers/main.yml and community.mongo/tests/integration/targets/setup_mongodb/handlers/main.yml differ
> Files mongodb/tests/integration/targets/setup_mongodb/tasks/main.yml and community.mongo/tests/integration/targets/setup_mongodb/tasks/main.yml differ
> Only in community.mongo/tests/integration/targets: setup_mongodb_v4
> Files mongodb/tests/integration/targets/setup_remote_tmp_dir/handlers/main.yml and community.mongo/tests/integration/targets/setup_remote_tmp_dir/handlers/main.yml differ
> Files mongodb/tests/integration/targets/setup_remote_tmp_dir/tasks/default-cleanup.yml and community.mongo/tests/integration/targets/setup_remote_tmp_dir/tasks/default-cleanup.yml differ
> Files mongodb/tests/integration/targets/setup_remote_tmp_dir/tasks/default.yml and community.mongo/tests/integration/targets/setup_remote_tmp_dir/tasks/default.yml differ
> Files mongodb/tests/integration/targets/setup_remote_tmp_dir/tasks/main.yml and community.mongo/tests/integration/targets/setup_remote_tmp_dir/tasks/main.yml differ
> Only in mongodb/tests/: output
> Only in community.mongo/tests/: requirements.yml
> Files mongodb/tests/sanity/ignore-2.10.txt and community.mongo/tests/sanity/ignore-2.10.txt differ
> Files mongodb/tests/sanity/ignore-2.9.txt and community.mongo/tests/sanity/ignore-2.9.txt differ
